name: Docker Build & Scan

on:
  workflow_dispatch:
  push:
    paths:
      - 'dockerfiles-repo/**'

jobs:
  docker-build-scan:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    
    steps:
      - name: Checkout Dockerfiles Repo
        uses: actions/checkout@v3
        with:
          repository: <your-org>/dockerfiles-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Install Hadolint
        run: |
          wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint
      - name: Lint Dockerfile
        run: hadolint dockerfiles-repo/app/Dockerfile

      - name: Build Docker Image
        run: |
          IMAGE_NAME=myapp:latest
          docker build -t $IMAGE_NAME dockerfiles-repo/app

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.44.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.44.2_Linux-64bit.deb
      - name: Scan Docker Image
        run: trivy image myapp:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag myapp:latest ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest

      - name: Push Docker Image to GHCR
        run: |
          docker tag myapp:latest ghcr.io/${{ github.repository_owner }}/myapp:latest
          docker push ghcr.io/${{ github.repository_owner }}/myapp:latest