name: Shared GHCR Build & Trivy with Slack
on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
    secrets:
      GHCR_PAT:
        required: true
      SLACK_WEBHOOK:
        required: true
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build & Push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/app:latest
          docker build -f ${{ inputs.dockerfile }} -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE }}
          format: table
          output: trivy-report.txt
      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt
      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v2
        with:
          webhook-type: incoming-webhook
          payload: |
            {"text": "Docker build & scan → *${{ job.status }}*"}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}