name: Shared GHCR Build & Trivy
on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      registry:
        required: false
        type: string
        default: "ghcr"
    secrets:
      GHCR_PAT:
        required: false
      DOCKER_HUB_USERNAME:
        required: false
      DOCKER_HUB_TOKEN:
        required: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Login to GHCR
        if: inputs.registry == 'ghcr'
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Login to Docker Hub
        if: inputs.registry == 'dockerhub'
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      
      - name: Build Docker image
        run: |
          if [ "${{ inputs.registry }}" = "ghcr" ]; then
            IMAGE=ghcr.io/${{ github.repository_owner }}/app:latest
          else
            IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/app:latest
          fi
          docker build -f ${{ inputs.dockerfile }} -t $IMAGE .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
      
      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE }}
      
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE }}
          format: table
          output: trivy-report.txt
      
      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt