name: Shared DockerHub Build & Trivy
on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      
      - name: Build Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/app:latest
          docker build -f ${{ inputs.dockerfile }} -t $IMAGE .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
      
      - name: Push Docker image
        run: docker push ${{ env.IMAGE }}
      
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE }}
          format: table
          output: trivy-report.txt
      
      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt

      - name: Notify Slack
        if: always() # send notification even if job fails
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":whale: *DockerHub Build & Trivy Scan Completed*",
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "${{ job.status }}",
                      "short": true
                    },
                    {
                      "title": "Image",
                      "value": "${{ env.IMAGE }}",
                      "short": false
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
