name: Shared Docker Workflow

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerhub_username:
        required: true
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: true
      GHCR_TOKEN:
        required: true
      SLACK_WEBHOOK:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io

      - name: Build Docker image
        run: |
          docker build -t ${{ inputs.image_name }}:latest .

      - name: Push to DockerHub
        run: |
          docker tag ${{ inputs.image_name }}:latest ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:latest
          docker push ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:latest

      - name: Push to GHCR
        run: |
          docker tag ${{ inputs.image_name }}:latest ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:latest

      - name: Run Hadolint on Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image_name }}:latest
          format: 'table'
          exit-code: '0'

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Build and Push completed for ${{ inputs.image_name }}"
